### ISSUE TITLE
What is the release process?

### ISSUE THREAD

**Issue by tnguyensanger** [phe-genomics/variant_definitions#12]
Are new releases created for each new VOC/VUI definition?  If not, how are VOCs/VUI definitions grouped into a release?

**Comment by nickloman** [comment]
Yes, new VOC/VUI definitions should get a new release package. I think we might be behind by one release at the moment however.

**Comment by nickloman** [comment]
Expect a release today or tomorrow to cover B.1.1.529 (potentially called Nu).

**Comment by tnguyensanger** [comment]
Thanks!

**Comment by DrYak** [comment]
Hi, any news about Omicron/B.1.1.529 in variant_defitiions ? (yup, apparently WHO skiped both Nu and Xi)

(As a side note, [here is a quick'n'dirty list of mutation common among the B.1.1.529 sequences in GISAID](https://github.com/cbg-ethz/cojac/blob/c1ca99fed58f0a4b32adc8ae9782caff3fe92fcd/voc/za2_mutations_temp.yaml#L8) that our PhD student @dr-david has compiled. Might be useul to some)

**Comment by nickloman** [comment]
A definition file has just been posted as part of release 0.6:
https://github.com/phe-genomics/variant_definitions/releases/tag/0.6

Many thanks!
