### ISSUE TITLE
how to interpret ````requires```` tag

### ISSUE THREAD

**Issue by tnguyensanger** [phe-genomics/variant_definitions#13]
In https://github.com/phe-genomics/variant_definitions/blob/main/variant_yaml/curtain-oasis.yml, there is a clause

````
requires: empathy-serve
````

How should we interpret the ````requires```` tag?  

If a sample only contains a 'probable' amount of required mutations according to the empathy-serve (VOC-21APR-02 / B.1.617.2) calling-definition, but it also contains all 3 of the required mutations for the curtain-oasis (VUI-21OCT-01 / AY.4.2) calling-definition, is it considered to be 'confirmed' as AY.4.2?   Or just 'probable', or neither?

**Comment by nickloman** [comment]
Sorry this isn't very clear and we will update the documentation accordingly but yes, you should also report a confirmed or probably from `empathy-serve`

**Comment by tnguyensanger** [comment]
Thanks!

**Comment by nickloman** [comment]
A clarification has been added to the README for release 0.6.1:
https://github.com/phe-genomics/variant_definitions/releases/tag/0.6.1
