### ISSUE TITLE
Contact information is outdated

### ISSUE THREAD

**Issue by lenaschimmel** [phe-genomics/variant_definitions#18]
The README still names covid19genomics@phe.gov.uk as contact email and lists several contributors as afiliated to PHE.

Since Public Health England has been in October 2021 and the hostname phe.gov.uk is no longer registered, this makes it hard to see who is responsible for this repository.

**Comment by grovesn** [comment]
Contact information has been updated please use genomicspublichealthanalysis@ukhsa.gov.uk
