### ISSUE TITLE
Missing SNPs

### ISSUE THREAD

**Issue by pr0kary0te** [phe-genomics/variant_definitions#9]
Am I correct in thinking that only selected SNPs/indels are displayed in some lineages?  For example, B.1.1.7 + E484K (unloved-crouton) doesn't seem to share any changes with it's close relative B.1.1.7 (denture-daughter).  Is it the case that only SNPs which define unloved-crouton from denture-daughter are shown?   If this is case, is it possible to link these so that unloved-crouton is known to have all variants in denture-daughter? Alternatively, it would be useful if the curation could show all SNPs present relative to wuhan hu-1.  Our lab design variant-specific SNP panels and it has been a real headache curating the variants manually for this purpose.

**Comment by nickloman** [comment]
Thanks for the note. We've been discussing the idea of including all the lineage-defining mutations in the definitions to aid such applications. We think we can do it although it needs a little bit of thinking about because we will need to set some kind of frequency threshold for mutations that are not completely fixed in the lineage (for whatever reason).

**Comment by pr0kary0te** [comment]
Thanks for the speedy reply!  I hope you can include all variants in each file, but I understand the problems caused by non-fixed mutations, which clearly complicate the definition of a lineage.  For information, here is one of the output files I obtained when parsing your data: you can see how the SNPs shown look quite sparse. Ideally we'd want all cells to be filled in with either wuhan ref allele or known alternate (even if this is a IUPAC ambiguity code for a non-fixed SNP). https://github.com/pr0kary0te/SARSvariants2probes/blob/main/variant_probe_matrix.txt

**Comment by nickloman** [comment]
Can I just check whether you mean reporting all SNPs/indels that are fixed (for some definition of fixed) in the lineage, or all SNPs/indels ever seen within that lineage? The former is more what I was thinking about doing. The latter would be harder and also need regular updating.
